language: scala
scala:
- 2.11.6
sudo: false
env:
  global:
  - secure: AtBRXOhHnDA22/AdZ0xRL+78L4k2UuTZv7G/jutpBPd/uiiFHrNh+Df6s1Ay0qd7n/vCFxC+4GPTPNZf75ymjjvZMUM+QoUwyLLf/Wi0sFk9i1Z1bJQ+izLKwEeUTToA2H/7A1JkKCFfu5bQxBxJH/s9nsWNTqt+P28l8Ej9NDc=
  - secure: bSghQ1A+dVIGJg1ZMi1GpA0LfgJvNQO0a3rCyyf/u6Et6a1MO62dUuwSij4QVDU9omOVNmBub2KM5jFq9fD5884gCWNWCqvqztJmJOpC4w/Ghnikipzzka8BbUlrj68jokKeuR5scnailsPFD4v1JwbXaS1d10FaHs4J0RfP04c=
  - secure: A4RkKzHM5oHvMkKRJT6M5hle5GgPtzCtqCbHn7YIHbkve+zEka1zWq7jXk76MgYSY0ra472CCzYdBglDmBSHTwwGRPXZsgdjinPyxZgOBZSndW2UQo1IqYFXSO0xh2fxsUuwAGK39Uhak1/Qz6p4VqDI6FtFn1vxSEeGstk3dtM=
  - secure: TZ1p3YNM+SlxovbCfBIDFQ729Sz3M4IfbQBg7nf2+2/mL3rLXJ/AE4v3MpEYxeZTFDYJsf1mQ/0L1roAxJelkPNtdSDzEy/R1H4t6/JYgg/Dw+ZvmwuiV804ebF5n2LVCsVK/qmh43iTBbYPNXQ21OEarL1Anh5vnNJhR7o+ZkM=
script: $TRAVIS_BUILD_DIR/travis/build.sh
