language: scala
scala:
- 2.11.6
- 2.10.4
env:
  global:
  - secure: Q6bu8Rp2+HvnrGReNtmYxP2L6D3FoaxPpKWle79axrwFJiG0F6Hpp8erdACAeXguBiIr1vVYELlMZosxdKulJjDHV91U2uVF7GsPFdXZhQAUfwk9WLcMJxBz2reSA6LaLH92n+YMcGD95cAtfeCiSaha0v7js+5vNyWzfAlF1P8=
  - secure: GERqiicWh/mZDbs0ARGHoBru9dPq034NwkVhXPbf6w1JE++cwWyHsQzHNPSoP9JBNXoonvo0yOCbWwXHd6flzwB9kujp2rtJndYbvHfTO/33BWFDlC3+Ckr2ysEi0GySYLg/e/BZKrdAdEH0+2rrvOBD1ng4jtTPE864vMxxxw8=
  - secure: dqFb6xvGxactxLLDjMeiBwWtSOOAHsJhB1gLpIsSx3HmcuNAIwakw6iqYRp10ggJZfc86vq0ofBGMr+oG0IFOUSwE8co6KWaw2pzXX9BTeh2oSEIZltnvHNVKnyYDce9Pxs00yOUZgZG/IcBmYA9dWbnd1EeyufoyWQrg5iatEg=
script: "$TRAVIS_BUILD_DIR/travis/build.sh"
